### ISSUE TITLE
howToPlay.py errors at end instead of playing game

### ISSUE THREAD

**Issue by f-hicks** [Sulaiman-Gaskell/Spelling-game#11]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\brozorb\\Downloads\\Spelling-game-Releases\\Spelling_Game.py'
i think it is classicMode.py instead of Spelling_Game.py

**Comment by f-hicks** [comment]
#12 fixes this

**Comment by Sulaiman-Gaskell** [comment]
Fixed in a new release im working on
