### ISSUE TITLE
[feature request] add timer for how long it takes to spell and reward points from how fast you do it

### ISSUE THREAD

**Issue by f-hicks** [Sulaiman-Gaskell/Spelling-game#14]

**Comment by Sulaiman-Gaskell** [comment]
k ill do that after ive finished with 2.1.1

**Comment by Sulaiman-Gaskell** [comment]
After reviewing this i can definitely show the time length bu not sure about the pointing system. Ill see what i can do

**Comment by f-hicks** [comment]
You should just be able to find the percentage of time it took over the max time for that game mode, then times that percentage multiplier by the number of points you would get

**Comment by Sulaiman-Gaskell** [comment]
Yes i could do that except that finding the time taken for the person to answer could be an issue

**Comment by f-hicks** [comment]
https://stackoverflow.com/questions/37370146/timing-how-long-it-takes-to-get-an-input-python
________________________________

**Comment by Sulaiman-Gaskell** [comment]
K will do tomorrow

**Comment by Sulaiman-Gaskell** [comment]
Will finish other features tho first

**Comment by Sulaiman-Gaskell** [comment]
Done
